DB_SERVICE=restates_db
WEB_SERVICE=restates_web

COMPOSE=docker-compose -f infrastructure/docker/compose/dev.yml

web:
	$(COMPOSE) up -d $(WEB_SERVICE)

db:
	$(COMPOSE) up -d $(DB_SERVICE)
	@make ps

log-web:
	$(COMPOSE) logs $(WEB_SERVICE)

log-db:
	$(COMPOSE) logs $(DB_SERVICE)

down:
	$(COMPOSE) down

ps:
	$(COMPOSE) ps

db-console:db
	$(COMPOSE) exec $(DB_SERVICE) mongo restates
